[project]
name = "state-eval"
version = "0.1.0"
description = "Evaluation metrics for single-cell perturbation predictions"
readme = "README.md"
authors = [
    { name = "Abhinav Adduri", email = "abbhinav.adduri@arcinsistute.org" },
    { name = "Yusuf Roohani", email = "yusuf.roohani@arcinsistute.org" },
    { name = "Noam Teyssier", email = "noam.teyssier@arcinsistute.org" },
]
requires-python = ">=3.9"
dependencies = [
    "adjustpy>=0.1.1",
    "ott-jax>=0.5.0",
    "pyyaml>=6.0.2",
    "scanpy>=1.10.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
run_eval = "state_eval.__main__:main"
