name: "CI"

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Setup Python
        run: |
          uv python install 3.12
          uv venv

      - name: Install project
        run: |
          uv sync --all-extras --dev
          uv tool install .

      - name: Check formatting
        run: |
          uv run ruff format --check

      - name: Test with pytest
        run: |
          uv run pytest -v

      - name: Test cli usage
        run: |
          uv run run_eval --help
