name: "CI"

on: [push, pull_request]

jobs:
  all_jobs:
    runs-on: ubuntu-latest
    needs: [formatting, pytest, cli-test]
    steps:
      - name: Complete
        run: echo "Complete"

  install-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_PDEX }}

      - name: Configure GitHub SSH
        run: |
          mkdir -p ~/.ssh
          echo "Host github.com" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Verify SSH connection
        run: ssh -T git@github.com || true # Will exit with error code 1 even when successful

      - name: install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
          python-version: "3.12"

      - name: install dependencies
        run: |
          uv sync --all-extras --dev

  formatting:
    runs-on: ubuntu-latest

    needs: [install-job]

    steps:
      - uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
          python-version: "3.12"

      - name: install dependencies
        run: |
          uv sync --all-extras --dev

      - name: run formatting
        run: |
          uv run ruff format --check

  pytest:
    runs-on: ubuntu-latest

    needs: [install-job]

    steps:
      - uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
          python-version: "3.12"

      - name: install dependencies
        run: |
          uv sync --all-extras --dev

      - name: run pytest
        run: |
          uv run pytest -v

  cli-test:
    runs-on: ubuntu-latest

    needs: [install-job]

    steps:
      - uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
          python-version: "3.12"

      - name: install dependencies
        run: |
          uv sync --all-extras --dev

      - name: run cli tests
        run: |
          uv run run_eval --help
